apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: furweb
  ports:
  - name: furweb1
    port: 3000
    targetPort: 3000
    nodePort: 30001
  - name: furweb2
    port: 5000
    targetPort: 5000
    nodePort: 30002

